services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sokolkov_netology
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8090:8090"
    environment:
      DB_HOST: mysql
      DB_USER: docker_user
      DB_PASSWORD: password
      DB_NAME: sokolkov_netology
    depends_on:
      mysql:
        condition: service_healthy
